interface enp1s0
{
    AdvSendAdvert on;
    
    # Send advertisements every 10-30 seconds
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 10;

    # Managed DHCPv6 Flag (tells the client to use Kea DHCPv6 for IP addresses)
    AdvManagedFlag on;
    
    # Other Configuration Flag (tells the client to look for DNS/boot options via DHCPv6)
    AdvOtherConfigFlag on;

    # Announce your IPv6 Private Lab Prefix
    prefix fd00:22::/64
    {
        AdvOnLink on;
        AdvAutonomous off; # Allows standard SLAAC configuration
        AdvRouterAddr on;
    };
};
