name: Build and publish FRRouter

on:
  workflow_dispatch:
  push:
    tags:
      - "frr_*"

env:
  GITHUB_REPOSITORY: HIRO-MicroDataCenters-BV/platform-build

permissions:
  contents: write

jobs:
  frr_build:
    name: FRRouting build
    runs-on: ${{ matrix.config.run_os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # - run_os: ubuntu-latest
          #   release_os: ubuntu-22.04
          #   arch: x86_64
          #   platform: amd64
          #   container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-22.04-linux-amd64-latest

          # - run_os: ubuntu-latest
          #   release_os: ubuntu-24.04
          #   arch: x86_64
          #   platform: amd64
          #   container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-24.04-linux-amd64-latest

          - run_os: ubuntu-latest
            release_os: ubuntu-26.04
            arch: x86_64
            platform: amd64
            container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-26.04-linux-amd64-latest

          # - run_os: ubuntu-26.04-arm
          #   release_os: ubuntu-22.04
          #   arch: arm64
          #   platform: arm64
          #   container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-22.04-linux-arm64-latest

          # - run_os: ubuntu-26.04-arm
          #   release_os: ubuntu-24.04
          #   arch: arm64
          #   platform: arm64
          #   container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-24.04-linux-arm64-latest

          - run_os: ubuntu-26.04-arm
            release_os: ubuntu-26.04
            arch: arm64
            platform: arm64
            container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-26.04-linux-arm64-latest

    container:
      image: ${{ matrix.config.container }}
      options: --user 0

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build And Package
        run: |
          ./frr/bin/build.sh determine_version
          ./frr/bin/build.sh build ${{ matrix.config.release_os }}

      - name: Collect deb packages
        run: |
          mkdir -p frr-artifacts
          DISTRO="${{ matrix.config.release_os }}"

          for f in ./frr/target/artifacts/*.deb; do
            base=$(basename "$f" .deb)
            cp "$f" "frr-artifacts/"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-${{ matrix.config.release_os }}-${{ matrix.config.platform }}
          path: frr-artifacts/*.deb

  release:
    name: FRRouting Release
    runs-on: ubuntu-latest
    needs: frr_build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build And Package
        run: |
          ./frr/bin/build.sh determine_version
          VERSION=$(cat ./frr/target/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: FRRouting ${{ env.VERSION }}
          files: release-artifacts/**/*.deb