name: Build and publish IPXE build

on:
  workflow_dispatch:
  push:
    tags:
      - "ipxe_*"

env:
  GITHUB_REPOSITORY: HIRO-MicroDataCenters-BV/platform-build

permissions:
  contents: write

jobs:
  ipxeboot:
    name: iPXE Boot UEFI
    runs-on: ${{ matrix.config.run_os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - run_os: ubuntu-latest
            release_os: ubuntu-22.04
            arch: x86_64
            container: ghcr.io/hiro-microdatacenters-bv/platform-build:ubuntu-22.04-linux-amd64-latest

    container:
      image: ${{ matrix.config.container }}
      options: --user 0

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ./ipxe/bin/build.sh determine_version
          ./ipxe/bin/build.sh build

      - name: Package
        run: |
          ./ipxe/bin/build.sh package

      # - name: Release
      #   env:
      #     GH_REPO: ${{ env.GITHUB_REPOSITORY }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release create "${{ github.ref_name }}" --verify-tag --draft \
      #         --title "$(cat version/relname.txt)" \
      #         --notes-file version/relnotes.md \
      #         bin-combi/ipxe.iso bin-combi/ipxe.usb \
      #         bin-combi/ipxe-arm64-sb.iso bin-combi/ipxe-arm64-sb.usb \
      #         bin-combi/ipxe-loong64-sb.iso bin-combi/ipxe-loong64-sb.usb \
      #         bin-combi/ipxe-riscv64-sb.iso bin-combi/ipxe-riscv64-sb.usb \
      #         bin-combi/ipxe-x86_64-sb.iso bin-combi/ipxe-x86_64-sb.usb \
      #         bin-combi/ipxeboot.tar.gz


      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ env.VERSION }}
      #     name: Release ${{ env.VERSION }}
      #     files: release-artifacts/**/*.deb